config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root to: "home#welcome"

  devise_for :users
  resources :users, only: [:show]
  resources :home, :only => [:welcome, :index]
  resources :conversations, :only => [ :show]
  resources :messages, only: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
        can :access, :rails_admin       # only allow admin users to access Rails Admin
        can :dashboard 
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord

  belongs_to :sender, class_name: 'User'
  belongs_to :receiver, class_name: 'User'

  has_many :messages, -> { order(created_at: :desc) }, dependent: :destroy

  # validates :sender, uniqueness: {scope: :receiver}

  scope :participating, -> (user) do
    where("(conversations.sender_id = ? OR conversations.receiver_id = ?)", user.id, user.id)
  end

  # scope :between, -> (sender_id, receiver_id) do
  #   where(current_user_id: sender_id, receiver_id: receiver_id).or(where(current_user_id: receiver_id, receiver_id: sender_id)).limit(1)
  # end

  def other_user(current_user)
    if self.sender_id == current_user.id
      return self.receiver
    else
      return self.sender
    end
  end

  def with(current_user)
    sender == current_user ? receiver : sender
  end

end

app/models/message.rb
class Message < ApplicationRecord

  belongs_to :conversation
  belongs_to :user

  validates :content, presence: true
  
end

app/models/user.rb
class User < ApplicationRecord

  has_many :messages, dependent: :destroy

  has_many :sent_conversations, class_name: 'Conversation', foreign_key: 'sender_id'
  has_many :received_conversations, class_name: 'Conversation', foreign_key: 'receiver_id'

  validates_uniqueness_of :user_name, :case_sensitive => false
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  def between(rec_id)
    @rec_id = rec_id.to_i
    @convos = Conversation.all
    @convos.each do |c|
      if (c.sender_id == self.id && c.receiver_id == @rec_id)
        return c
      elsif (c.receiver_id == self.id && c.sender_id == @rec_id)
        return c
      elsif (c.sender_id == self.id && c.receiver_id == self.id)
        return c
      # else
      #   return false
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(user)
    home_index_path
  end

  def configure_permitted_parameters
    added_attrs = [:user_name, :trainer, :admin, :email, :password, :password_confirmation, :remember_me, :current_password,]
      devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
      devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  def index
    @conversations = Conversation.participating(current_user).order('updated_at DESC')
  end

  before_action :set_conversation, except: [:index]


  def show
    @message = Message.new
  end

  private

  def set_conversation
    @conversation = Conversation.find_by(id: params[:id])
  end

  def check_participating!
    redirect_to root_path unless @conversation && @conversation.participates?(current_user)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
    @conversations = Conversation.participating(current_user)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :find_conversation!

  def new
    @message = Message.new()
  end
  def create
    @message = current_user.messages.build(message_params)
    if current_user.between((params['receiver_id']).to_i)
      @conversation = current_user.between((params['receiver_id']).to_i)
    elsif current_user.between(current_user.id)
      @conversation = current_user.between(current_user.id)
    else
      @conversation = Conversation.create!(sender_id: current_user.id, receiver_id: (params['receiver_id']))
    end
    @message.conversation_id = @conversation.id
    @message.save!

    redirect_to conversation_path(@conversation)
  end

  private

  def message_params
    params.require(:message).permit(:content, :sender_id, :receiver_id)
  end

  def find_conversation!
    @conversation = Conversation.find_by(id: params[:conversation_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @message = Message.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/conversations/show.html.erb
<h1>Messages with <%= @conversation.with(current_user).user_name %></h1>


  <div id="conversation-body">
    <% @conversation.messages.each do |message| %>
      <%= message.content %>
      <%= message.created_at %>
      <br>
    <% end %>
  </div>

  <%= form_for @message do |f| %>
    <%= hidden_field_tag 'receiver_id', @conversation.other_user(current_user).id%>
    <%= hidden_field_tag 'conversation_id', @conversation.id %>

    <%= f.label :content %>
    <%= f.text_area :content %>

    <%= f.submit %>
  <% end %>

app/views/home/index.html.erb
<div class="col-xs-6 well current-chat">
  <h1>Your current conversations</h1>

  <% if @conversations.any? %>
    <h4>Click a conversation to send a new message.</h4>
    <% @conversations.each do |convo| %>
    <%= link_to "Messages with #{convo.other_user(current_user).user_name}  (#{convo.messages.length} messages)",  conversation_path(convo) %>
    <br>
    <% end %>
  <% else %>
    <h4>You have no conversations yet</h4>
  <% end %>
</div>
<div class="col-xs-5 well new-chat">
  <h1>Start a new conversation</h1>
  <h4>With a trainer:</h4>
  <div class="trainers">
    <% @users.each do |u| %>
      <% if (u.trainer) && (u != current_user) %>
        <%= link_to u.user_name, user_path(u) %>
        <br>
      <% end %>
    <% end %>
  </div>
  <h4>With another member:</h4>
  <div class="members">
    <% @users.each do |u| %>
      <% if (!u.trainer) && (u != current_user) %>
        <%= link_to u.user_name, user_path(u) %>
      <% end %>
      <br>
    <% end %>
  </div>
</div>

app/views/home/welcome.html.erb
<div class="well welcome">
  <% if !current_user %>
  <h1>Welcome, please sign in!</h1>

  <%= link_to 'Sign In', new_user_session_path %>
  <p>Or</p>
  <%= link_to 'Sign Up', new_user_registration_path %>
  <% else %>

  <h1>Welcome, <%= current_user.user_name %>!</h1>
  <%= link_to "Chat!", home_index_path %>

  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FitsmindMessagePrototype</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="jumbotron">
        <h1>Welcome to FitsMind Messaging!</h1>
        <h4>Combining Mental and Physical Training</h4>
        <div class="collapse navbar-collapse" id="navbar-collapse-1">
          <ul class="nav navbar-nav navbar-left">
            <% if current_user && current_user.admin %>
              <li><%= link_to 'Admin', rails_admin_path %></li>
            <% end %>
          </ul>

          <ul class="nav navbar-nav navbar-right">
              <% if current_user %>
              <li><%= link_to 'Chat', home_index_path %></li>
              <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
              <% else %>
              <li><%= link_to 'Login', new_user_session_path %></li>
              <% end %>
          </ul>
        </div>
      </div>

        <%= yield %>


    </div>

  </body>
</html>

app/views/users/show.html.erb
Here is your user. Message to come.
<h1>New message to <%= @user.user_name %></h1>

<%= form_for @message do |f| %>
  <%= hidden_field_tag 'receiver_id', @user.id %>

  <%= f.label :content %>
  <%= f.text_area :content %>

  <%= f.submit %>
<% end %>